sequences = {'a_tract_21mer': {'guide': 'AAAAAAAAAAAAAAAAAAAAA', 
                               'target': 'TTTTTTTTTTTTTTTTTTTTT'},
             'g_tract_21mer': {'guide': 'GGGGGGGGGGGGGGGGGGGGG', 
                               'target': 'CCCCCCCCCCCCCCCCCCCCC'},
             'atat_21mer':    {'guide': 'ATATATATATATATATATATA', 
                               'target': 'TATATATATATATATATATAT'},
             'gcgc_21mer':    {'guide': 'GCGCGCGCGCGCGCGCGCGCG', 
                               'target': 'CGCGCGCGCGCGCGCGCGCGC'},
             'tgtg_21mer':    {'guide': 'TGTGTGTGTGTGTGTGTGTGT',
                               'target': 'ACACACACACACACACACACA'},
             'ctct_21mer':    {'guide': 'CTCTCTCTCTCTCTCTCTCTC', 
                               'target': 'GAGAGAGAGAGAGAGAGAGAG'}}